DELETE http://localhost:4000/api/blogs/6065c4ea12e13c2cc4a073b9
Authorization: bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R5IiwiaWQiOiI2MDY1YzA4MDdjZjU3ZjU1Zjg2MDMwZjIiLCJpYXQiOjE2MTczNzY5NDAsImV4cCI6MTYxNzM4MDU0MH0.9jSQ9FHFfNNLg2XKnBvs_6nmoSJKiyY7PGSd8sLCbfA
Content-Type: application/json
